
aliyun:
  accessKeyId: xxxxx
  accessKeySecret: xxxxx

rocketmq:
  configs:
    erp:
      nameSrvAddr: http://localhost:80
      accessKey: ${aliyun.accessKeyId}
      secretKey: ${aliyun.accessKeySecret}
      enable: true
    file:
      nameSrvAddr: http://localhost:80
      accessKey: ${aliyun.accessKeyId}
      secretKey: ${aliyun.accessKeySecret}
      enable: true
  producer:
    orderRewrite:
      group: ERP_ORDER_REWRITE
      topic: ERP_ORDER_REWRITE
    file:
      topic: FILE
      group: FILE
  consumer:
    orderRewrite:
      topic: ERP_ORDER_REWRITE
      group: ERP_ORDER_REWRITE